DLS_Technologies/ViewModels/ExpenseViewModels/ExpenseFormViewModel.cs
using DLS_Technologies.Models;
using DLS_Technologies.Models.ExpensesModels;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace DLS_Technologies.ViewModels
{
    public class ExpenseFormViewModel
    {
        public int Id { get; set; }

        [Required]
        public string Name { get; set; }

        public ExpenseForm ExpenseForm { get; set; }

        public IEnumerable<Expense> Expenses { get; set; }

        [Display(Name = "Expense Forms")]
        public IEnumerable<ExpenseForm> ExpenseForms { get; set; }

        public IEnumerable<ExpenseType> ExpenseTypes { get; set; }

        [Display(Name = "Expense Type")]
        public ExpenseType ExpenseType { get; set; }
        
        public int ExpenseTypeId { get; set; }

        public Expense Expense { get; set; }

        public double? TotalCost { get; set; }
        
        public ApplicationUser User { get; set; }

        public string UserId { get; set; }

        public DateTime? DateAdded { get; set; }      

    }
}

DLS_Technologies/Controllers/Api/Expenses/ExpenseFormsController.cs
using DLS_Technologies.Models;
using DLS_Technologies.Models.ExpensesModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Http.Formatting;
using System.Web.Http;

namespace DLS_Technologies.Controllers.Api
{
    public class ExpenseFormsController : ApiController
    {
        private ApplicationDbContext _context;

        public ExpenseFormsController()
        {
            _context = new ApplicationDbContext();
        }


        // DELETE api/expenseforms/1
        [HttpDelete]
        [System.Web.Mvc.ValidateAntiForgeryToken]
        public void DeleteExpenseForm(int id)
        {
            var expenseFormInDb = _context.ExpenseForms.SingleOrDefault(e => e.Id == id);

            if (expenseFormInDb == null)
                throw new HttpResponseException(HttpStatusCode.NotFound);

            _context.ExpenseForms.Remove(expenseFormInDb);
            _context.SaveChanges();
        }

        // UPDATE api/expenseforms/1
        [HttpPut]
        [System.Web.Mvc.ValidateAntiForgeryToken]
        public void UpdateExpenseFormName(FormDataCollection formData)
        {
            var id = Convert.ToInt32(formData.Get("Id"));
            var name = formData.Get("Name");

            var expenseFormInDb = _context.ExpenseForms.SingleOrDefault(e => e.Id == id);

            if (expenseFormInDb == null)
                throw new HttpResponseException(HttpStatusCode.NotFound);

            expenseFormInDb.Name = name;
            _context.SaveChanges();
        }



    }
}

DLS_Technologies/Controllers/Expenses/ExpenseFormsController.cs
using DLS_Technologies.Models;
using DLS_Technologies.Models.ExpensesModels;
using DLS_Technologies.ViewModels;
using System.Data.Entity;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using System.Net;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Threading.Tasks;
using Microsoft.AspNet.Identity.EntityFramework;
using System.Net.Http.Formatting;

namespace DLS_Technologies.Controllers
{

    /// <summary>
    /// TODO: Add validation for each HTTP Request.
    /// TODO: Use DTOs instead of domain model.
    /// </summary>


    public class ExpenseFormsController : Controller
    {
        /// Application DB context        
        protected ApplicationDbContext _context { get; set; }
       
        /// User manager - attached to application DB context        
        protected UserManager<ApplicationUser> _userManager { get; set; }

        public ExpenseFormsController()
        {
            _context = new ApplicationDbContext();
            _userManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(_context));
            
        }

        public ActionResult Index()
        {
            var _user = _userManager.FindById(User.Identity.GetUserId());
            var expenseForms = _context.ExpenseForms.Where(e => e.UserId == _user.Id).ToList();            

            return View(expenseForms);
        }                     
        
        // GET: Expenses
        [HttpPost]
        public ActionResult SaveExpenseForm(ExpenseFormViewModel expenseForm)
        {
            if (!ModelState.IsValid)            
                return View("Index");           


            var _user = _userManager.FindById(User.Identity.GetUserId());

            var expenseForms = _context.ExpenseForms.Where(e => e.UserId == _user.Id).ToList();          

            if (expenseForm.Id == 0)
            {
                var expenseFormToSave = new ExpenseForm
                {
                    Name = expenseForm.Name,
                    DateAdded = DateTime.Now,
                    TotalCost = 0,
                    UserId = _user.Id,
                    User = _user
                };
                _context.ExpenseForms.Add(expenseFormToSave);
            }                
            else
            {
                var _expenseFormInDb = _context.ExpenseForms.First(e => e.Id == expenseForm.Id);
                _expenseFormInDb.Name = expenseForm.Name;
            }

            _context.SaveChanges();          

            return RedirectToAction("Index");

        }

        public ActionResult ShowExpenses(int expenseFormId)
        {
            var expenseForm = _context.ExpenseForms.Include(e => e.User).SingleOrDefault(e => e.Id == expenseFormId);
            var viewModel = new ExpenseFormViewModel
            {
                ExpenseForm = expenseForm,
                Expenses = _context.Expenses.Include(e => e.ExpenseType).Where(e => e.ExpenseFormId == expenseFormId).ToList(),
                User = expenseForm.User
                
            };

            var name = !String.IsNullOrEmpty(viewModel.User.FullName) ? viewModel.User.FullName : viewModel.User.FirstName + " " + viewModel.User.LastName;

            ViewBag.Title = viewModel.ExpenseForm.Name + " - " + name;            

            return View("ShowExpensesForm", viewModel);
        }

        

    }
}

DLS_Technologies/Views/ExpenseForms/AddNewExpenseFormForm.cshtml
@model DLS_Technologies.ViewModels.ExpenseFormViewModel

@using (Html.BeginForm("SaveExpenseForm", "ExpenseForms"))
{

    @Html.ValidationSummary()
    @Html.AntiForgeryToken()


    @Html.HiddenFor(m => m.Id)
    @Html.HiddenFor(m => m.DateAdded)

    <button id="showNewExpenseFormBtn" class="btn btn-primary">Add New Expense Form</button>
    <br /><br />


    <div hidden="hidden" id="addNewExpenseFormBtn" class="form-group">
        @Html.LabelFor(m => m.Name)
        <div class="row">
            <div class="col-xs-3">
                <div class="input-group">
                    @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
                    <span class="input-group-btn">
                        <button class="btn btn-success" type="submit">Add</button>
                    </span>
                </div>
            </div>
        </div>
    </div>
}

DLS_Technologies/Views/ExpenseForms/Index.cshtml
@model IEnumerable<DLS_Technologies.Models.ExpensesModels.ExpenseForm>
@{
    ViewBag.Title = "Expenses";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h2>@ViewBag.Title</h2>
<hr />

@Html.Partial("_NewExpenseForm", new DLS_Technologies.ViewModels.ExpenseFormViewModel())
@{ 
    if (!Model.Any())
    {
        <h3>You have not created any Expense Forms.</h3>
    }
    else
    {
        <table id="expenseFormsTable" class="table table-hover table-bordered">
            <thead>
                <tr>
                    <th>Expense Form</th>
                    <th>Date Added</th>
                    <th>Total Cost</th>
                    <th>Edit</th>
                    <th>Delete</th>
                </tr>
            </thead>
            <tbody>
                @{ 
                    foreach (var form in Model)
                    {
                        <tr>
                            <td data-order="@form.DateAdded">@Html.ActionLink(@form.Name, "ShowExpenses", "ExpenseForms", new { expenseFormId = @form.Id }, null)</td>
                            <td>@form.DateAdded.Value</td>
                            <td>£@form.TotalCost.Value.ToString("0.00")</td>
                            <td><button data-expenseform-id="@form.Id" class="btn-link js-edit">Edit</button></td>
                            <td><button data-expenseform-id="@form.Id" class="btn-link js-delete">Delete</button></td>
                        </tr>
                    }
                }
            </tbody>
        </table>
    }
}

@section scripts {

    @Scripts.Render("~/scripts/formscripts/expenses/expenseforms-index.js")

}

DLS_Technologies/Views/ExpenseForms/ShowExpensesForm.cshtml
@model DLS_Technologies.ViewModels.ExpenseFormViewModel
@{  
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>@ViewBag.Title</h3>
<hr />
@Html.ActionLink("Back", "Index", "ExpenseForms")
<br /><br />
@Html.ActionLink("Add New Expense", "NewExpense", "Expenses", new { expenseFormId = Model.ExpenseForm.Id }, null )
<br /><br />
@{
    if (!Model.Expenses.Any())
    {
        <h4>No expenses have been added to this form.</h4>
    }
    else
    {
        @Html.HiddenFor(m => m.ExpenseForm.Id)
        @Html.HiddenFor(m => m.TotalCost)

        <table id="expensesTable" class="table table-bordered table-hover">
            <thead>
                <tr>
                    <th>Expense Type</th>
                    <th>Date</th>
                    <th>DateTime</th>
                    <th>Origin</th>
                    <th>Destion</th>
                    <th>Total Miles</th>
                    <th>Cost</th>  
                </tr>
            </thead>
            <tbody>
                @{ 
                    foreach (var expense in Model.Expenses)
                    {
                        
                        <tr data-expenseform-id="@expense.ExpenseFormId" data-expense-id="@expense.Id">
                            <td>@expense.ExpenseType.Name</td>
                            <td>@expense.Date.Value.ToShortDateString()</td>
                            <td>@expense.DateTime</td>
                            <th>@expense.Origin</th>
                            <th>@expense.Destination</th>
                            <td>@expense.TotalMiles</td>
                            <td>£@expense.Cost.Value.ToString("0.00")</td>
                        </tr>
                        
                    }
                }
            </tbody>
            
        </table>
    }
}

@section scripts {

    @Scripts.Render("~/scripts/formscripts/expenses/expenseforms-form.js")
}

DLS_Technologies/Views/ExpenseForms/_NewExpenseForm.cshtml
@model DLS_Technologies.ViewModels.ExpenseFormViewModel

@using (Html.BeginForm("SaveExpenseForm", "ExpenseForms"))
{

    @Html.ValidationSummary()
    @Html.AntiForgeryToken()


    @Html.HiddenFor(m => m.Id)
    @Html.HiddenFor(m => m.DateAdded)

    <button id="showNewExpenseFormBtn" class="btn btn-primary">Add New Expense Form</button>
    <br /><br />


   

    <div hidden="hidden" id="addNewExpenseFormBtn" class="form-group">
            @Html.LabelFor(m => m.Name)
                <div class="input-group" style="width:300px;">
                    @Html.TextBoxFor(m => m.Name, new { @class = "form-control", @placeholder = "Form Name.." })
                    <span class="input-group-btn">
                        <button class="btn btn-success" type="submit">Add</button>
                    </span>
                </div>
    </div>
    <br />
}