DLS_Technologies/Models/Customers/AccountType.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace DLS_Technologies.Models.Customers
{
    public class AccountType
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public byte Id { get; set; }

        public string Name { get; set; }

        public bool MonthlySiteVisit { get; set; }

    }
}

DLS_Technologies/Models/Customers/Customer.cs
using DLS_Technologies.Models.Customers;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace DLS_Technologies.Models
{
    public class Customer
    {
        public int Id { get; set; }

        [Required]
        [Display(Name = "Name:")]
        public string Name { get; set; }

        public AccountType AccountType { get; set; }

        [Required]
        [Display(Name = "Account Type:")]
        public byte AccountTypeId { get; set; }

        [Required]
        [Display(Name = "Contact on Site:")]
        public string ContactOnSite { get; set; }

        [Required]
        [Display(Name = "Email Address:")]
        public string EmailAddress { get; set; }

        [Required]
        [Display(Name = "Date Joined:")]
        public DateTime DateJoined { get; set; }

        [Required]
        [Display(Name = "Address:")]
        public string Address { get; set; }

        [Required]
        [Display(Name = "Post Code:")]
        public string PostCode { get; set; }

        [Required]
        [Display(Name = "Contact Information:")]
        public string ContactInfo { get; set; }

        [Display(Name = "Notes:")]
        public string Note { get; set; }

        [Display(Name = "Site Visit Date:")]
        public DateTime? MonthlySiteVisitDate { get; set; }
        
        
    }
}

DLS_Technologies/Models/Customers/CustomerServer.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace DLS_Technologies.Models.Customers
{
    public class CustomerServer
    {
        public int Id { get; set; }

        [Required]
        [Display(Name = "Server Name:")]
        public string ServerName { get; set; }

        [Required]
        [Display(Name = "Public IP Address:")]
        public string PublicIpAddress { get; set; }

        [Required]
        [Display(Name = "Private IP Address:")]
        public string PrivateIpAddress { get; set; }

        [Required]
        [Display(Name = "Port:")]
        public string Port { get; set; }

        [Required]
        [Display(Name = "Username:")]
        public string UserName { get; set; }

        [Required]
        [Display(Name = "Password:")]
        public string Password { get; set; }        

        public Customer Customer { get; set; }

        public int CustomerId { get; set; }
    }
}

DLS_Technologies/Models/Customers/SiteInfo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace DLS_Technologies.Models.Customers
{
    public class SiteInfo
    {
        public int Id { get; set; }

        public string NetworkInfo { get; set; }

        public string WifiInfo { get; set; }

        public string DomainInfo { get; set; }

        public Customer Customer { get; set; }

        public int CustomerId { get; set; }
    }
}

DLS_Technologies/Models/Customers/SiteInfoNote.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace DLS_Technologies.Models.Customers
{
    public class SiteInfoNote
    {
        public int Id { get; set; }

        [Required]
        [Display(Name = "Title:")]
        public string Title { get; set; }

        [Required]
        [Display(Name = "Note:")]
        public string Note { get; set; }

        public Customer Customer { get; set; }

        public int CustomerId { get; set; }
    }
}

DLS_Technologies/ViewModels/CustomerViewModels/CustomerViewModel.cs
using DLS_Technologies.Models.Customers;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace DLS_Technologies.ViewModels.CustomerViewModels
{
    public class CustomerViewModel
    {
        public int Id { get; set; }

        [Required]
        [Display(Name = "Name:")]
        public string Name { get; set; }        

        public IEnumerable<AccountType> AccountTypes { get; set; }

        [Required]
        [Display(Name = "Account Type:")]
        public byte AccountTypeId { get; set; }

        public AccountType AccountType { get; set; }

        [Required]
        [Display(Name = "Contact on Site:")]
        public string ContactOnSite { get; set; }

        [Required]
        [Display(Name = "Email Address:")]
        public string EmailAddress { get; set; }

        [Required]
        [Display(Name = "Date Joined:")]
        public DateTime DateJoined { get; set; }

        [Required]
        [Display(Name = "Address:")]
        public string Address { get; set; }

        [Required]
        [Display(Name = "Post Code:")]
        public string PostCode { get; set; }

        [Required]
        [Display(Name = "Contact Information:")]
        public string ContactInfo { get; set; }        
        
        [Display(Name = "Site Visit Date:")]
        public DateTime? MonthlySiteVisitDate { get; set; }        
        
        [Display(Name = "Notes:")]
        public string Note { get; set; }
    }


    
}

DLS_Technologies/Controllers/Api/Customers/CustomersController.cs
using DLS_Technologies.Models;
using DLS_Technologies.Models.Customers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Http.Formatting;
using System.Web.Http;
using System.Web.Helpers;
using DLS_Technologies.ViewModels.CustomerViewModels;



namespace DLS_Technologies.Controllers.Api.Customers
{
    public class CustomersController : ApiController
    {
        ApplicationDbContext _context;

        public CustomersController()
        {
            _context = new ApplicationDbContext();
        }        

        [HttpDelete]
        [System.Web.Mvc.ValidateAntiForgeryToken]
        public void DeleteCustomer(int id)
        {
            var customerInDb = _context.Customers.FirstOrDefault(e => e.Id == id);

            if (customerInDb == null)
                throw new HttpResponseException(HttpStatusCode.NotFound);

            _context.Customers.Remove(customerInDb);
            _context.SaveChanges();
        }        

        [HttpDelete]
        [System.Web.Mvc.ValidateAntiForgeryToken]
        public void DeleteNote(int id)
        {
            var note = _context.SiteInfoNotes.FirstOrDefault(n => n.Id == id);

            if (note == null)
                throw new HttpResponseException(HttpStatusCode.NotFound);

            _context.SiteInfoNotes.Remove(note);
            _context.SaveChanges();
        }

        [HttpDelete]
        [System.Web.Mvc.ValidateAntiForgeryToken]
        public void DeleteServer(int id)
        {
            var server = _context.CustomerServers.FirstOrDefault(s => s.Id == id);

            if(server == null)
                throw new HttpResponseException(HttpStatusCode.NotFound);

            _context.CustomerServers.Remove(server);
            _context.SaveChanges();
        }


    }
}

DLS_Technologies/Controllers/Customers/CustomersController.cs
using DLS_Technologies.Models;
using DLS_Technologies.Models.Customers;
using DLS_Technologies.ViewModels.CustomerViewModels;
using System;
using System.Data.Entity;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http.Formatting;
using System.Web;
using System.Web.Mvc;

namespace DLS_Technologies.Controllers.Customers
{
    /// <summary>
    /// TODO: Add validation for each HTTP Request.
    /// TODO: Use DTOs instead of domain model.
    /// TODO: Organize Methods.
    /// </summary>
    
    public class CustomersController : Controller
    {
        ApplicationDbContext _context;

        public CustomersController()
        {
            _context = new ApplicationDbContext();
        }

        // GET: Customer
        public ActionResult Index()
        {
            var customers = _context.Customers.ToList();
            return View(customers);
        }

        public ActionResult NewCustomer()
        {
            var accountTypes = _context.AccountTypes.ToList();

            var viewModel = new CustomerViewModel
            {
                AccountTypes = accountTypes,
                DateJoined = DateTime.Now,
                MonthlySiteVisitDate = DateTime.Now.AddDays(30)
            };

            return View("CustomerForm", viewModel);
        }

        public ActionResult GetCustomer(int id)
        {
            var customer = _context.Customers.Include(c => c.AccountType).Single(c => c.Id == id);
            return View("CustomerParent", customer);

        }

        public ActionResult Edit(int id)
        {
            var customer = _context.Customers.Single(c => c.Id == id);
            var accountTypes = _context.AccountTypes.ToList();

            var viewModel = new CustomerViewModel
            {
                Id = customer.Id,
                Name = customer.Name,
                AccountTypeId = customer.AccountTypeId,
                Address = customer.Address,
                PostCode = customer.PostCode,
                ContactInfo = customer.ContactInfo,
                ContactOnSite = customer.ContactOnSite,
                EmailAddress = customer.EmailAddress,
                DateJoined = customer.DateJoined,
                MonthlySiteVisitDate = customer.MonthlySiteVisitDate,
                Note = customer.Note,
                AccountTypes = accountTypes
            };


            return View("CustomerForm", viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Save(Customer customer)
        {
            var accountTypes = _context.AccountTypes.ToList();
            var viewModel = new CustomerViewModel
            {
                AccountTypes = accountTypes,
                DateJoined = DateTime.Now
            };

            if (!ModelState.IsValid) { return View("CustomerForm", viewModel); }            

            if(customer.Id == 0)
            {
                if (_context.Customers.Any(c => c.Name == customer.Name))
                {
                    ModelState.AddModelError("Name", "This customer already exists.");
                    return View("CustomerForm", viewModel);
                }

                if (customer.AccountTypeId != 1)                
                {
                    customer.MonthlySiteVisitDate = null;
                }

                var siteInfo = new SiteInfo { CustomerId = customer.Id };

                _context.SiteInfos.Add(siteInfo);
                _context.Customers.Add(customer);
                _context.SaveChanges();
                return View("CustomerParent", customer);
            }
            else
            {
                var custIndDb = _context.Customers.Single(c => c.Id == customer.Id);

                custIndDb.Id = customer.Id;
                custIndDb.Name = customer.Name;
                custIndDb.AccountTypeId = customer.AccountTypeId;
                custIndDb.Address = customer.Address;
                custIndDb.PostCode = customer.PostCode;
                custIndDb.ContactInfo = customer.ContactInfo;
                custIndDb.ContactOnSite = customer.ContactOnSite;
                custIndDb.EmailAddress = customer.EmailAddress;
                custIndDb.DateJoined = customer.DateJoined;
                custIndDb.MonthlySiteVisitDate = customer.MonthlySiteVisitDate;
                custIndDb.Note = customer.Note;

                _context.SaveChanges();
                return View("CustomerParent", customer);
            }            
        }

        public ActionResult GetNoteContent(int id)
        {
            if (id == 0)
                return Json(new { } );

            var note = _context.SiteInfoNotes.Single(n => n.Id == id).Note;
            var title = _context.SiteInfoNotes.Single(n => n.Id == id).Title;

            return Json(new { note = note, title = title }, JsonRequestBehavior.AllowGet) ;
        }

        [HttpPut]
        [ValidateAntiForgeryToken]
        public ActionResult SaveCustomerNote(int id, string note)
        {
            var customer = _context.Customers.Include(c => c.AccountType).Single(c => c.Id == id);

            if (!ModelState.IsValid)
            {
                return PartialView("_CustomerDetails", customer);
            }

            customer.Note = note;
            _context.SaveChanges();

            return PartialView("_CustomerDetails", customer);
        }

        [HttpPut]
        [ValidateAntiForgeryToken]
        public void SaveSiteInfoTabNote(int id, string note, string noteType)
        {
            var parsedType = noteType.Substring(0, noteType.Length - 4);

            var siteNotes = _context.SiteInfoNotes.Where(n => n.CustomerId == id).ToList();
            var servers = _context.CustomerServers.Where(s => s.CustomerId == id).ToList();
            var siteInfo = _context.SiteInfos.Single(s => s.CustomerId == id);

            var siteInfoVm = new SiteInfoViewModel
            {
                Id = siteInfo.Id,
                CustomerId = siteInfo.CustomerId,
                NetworkInfo = siteInfo.NetworkInfo,
                WifiInfo = siteInfo.WifiInfo,
                DomainInfo = siteInfo.DomainInfo,
                Notes = siteNotes
            };

            switch (parsedType)
            {
                case "Network":
                    siteInfo.NetworkInfo = note;
                    break;
                case "Wifi":
                    siteInfo.WifiInfo = note;
                    break;
                case "Domain":
                    siteInfo.DomainInfo = note;
                    break;
            }
            _context.SaveChanges();
        }

        [HttpPut]
        [ValidateAntiForgeryToken]
        public int SaveSiteInfoNote(int id, int noteId, string noteTitle, string noteContent)
        {
            var note = _context.SiteInfoNotes.FirstOrDefault(n => n.Id == noteId);

            if (note == null)
            {
                var siteInfoNote = new SiteInfoNote
                {
                    CustomerId = id,
                    Note = noteContent,
                    Title = noteTitle
                };
                _context.SiteInfoNotes.Add(siteInfoNote);
                _context.SaveChanges();
                return siteInfoNote.Id;
            }
            else
            {
                note.Title = noteTitle;
                note.Note = noteContent;
                _context.SaveChanges();
                return note.Id;
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SaveServer(CustomerServer server)
        {
            var servers = _context.CustomerServers.Where(s => s.CustomerId == server.CustomerId);

            var serverViewModel = new ServerViewModel
            {
                Servers = servers,
                CustomerId = server.CustomerId
            };

            if (server.Id == 0)
            {               
                _context.CustomerServers.Add(server);
                _context.SaveChanges();
                return View("_ServerInfo", serverViewModel);
            }
           
            var customer = _context.Customers.Single(c => c.Id == server.CustomerId);
            
            var serverInDb = _context.CustomerServers.SingleOrDefault(s => s.Id == server.Id);

            serverInDb.ServerName = server.ServerName;
            serverInDb.PublicIpAddress = server.PublicIpAddress;
            serverInDb.PrivateIpAddress = server.PrivateIpAddress;
            serverInDb.Port = server.Port;
            serverInDb.UserName = server.UserName;
            serverInDb.Password = server.Password;

            _context.SaveChanges();
            return View("_ServerInfo", serverViewModel);
        }        

        public ActionResult OpenRdp()
        {
            string address = Request.QueryString["address"];
            Response.ContentType = "application/octet-stream";
            Response.AppendHeader("Content-Disposition", string.Format("attachment; filename={0}.rdp", address));
            Response.Output.Write(string.Format(@"
                screen mode id:i:2
                session bpp:i:32
                compression:i:1
                keyboardhook:i:2
                displayconnectionbar:i:1
                disable wallpaper:i:1
                disable full window drag:i:1
                allow desktop composition:i:0
                allow font smoothing:i:0
                disable menu anims:i:1
                disable themes:i:0
                disable cursor setting:i:0
                bitmapcachepersistenable:i:1
                full address:s:{0}
                audiomode:i:0
                redirectprinters:i:1
                redirectcomports:i:0
                redirectsmartcards:i:1
                redirectclipboard:i:1
                redirectposdevices:i:0
                autoreconnection enabled:i:1
                authentication level:i:2

DLS_Technologies/Views/Customers/CustomerForm.cshtml
@model DLS_Technologies.ViewModels.CustomerViewModels.CustomerViewModel
@{
    ViewBag.Title = "New Customer";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@ViewBag.Title</h2>
<hr />
@Html.ActionLink("Back", "Index", "Customers", new { }, null)
<br /><br />

    @using (Html.BeginForm("Save", "Customers"))
    {
        @Html.ValidationSummary()
        @Html.AntiForgeryToken()
        <input type="hidden" id="Id" name="Id" value="@Model.Id">

        <div class="row">
            <div class="form-group col-sm-4">
                @Html.LabelFor(m => m.Name)
                @Html.TextBoxFor(m => m.Name, new { @class = "form-control", placeholder = "Name" })
            </div>            
            <div class="form-group col-sm-4">
                @Html.LabelFor(m => m.AccountTypeId)
                @Html.DropDownListFor(m => m.AccountTypeId, new SelectList(Model.AccountTypes, "Id", "Name", "1"), "Select Account Type", new { @class = "form-control", @onChange = "siteVisitCheck()" })
            </div>
            <div class="col-lg-offset-4"></div>
        </div>
        <div class="row">            
            <div class="form-group col-sm-4 site-visit-form" hidden="hidden">
                @Html.LabelFor(m => m.MonthlySiteVisitDate)
                @Html.TextBoxFor(m => m.MonthlySiteVisitDate, "{0:yyyy-MM-dd}", new { @class = "form-control", @type = "date" })
            </div>
            <div class="col-sm-offset-8"></div>
        </div>

        <div class="row" >
            <div class="form-group col-sm-4">
                @Html.LabelFor(m => m.ContactOnSite )
                @Html.TextBoxFor(m => m.ContactOnSite, new { @class = "form-control", @placeholder ="Contact Name"})
            </div>
            <div class="form-group col-sm-4">
                @Html.LabelFor(m => m.EmailAddress)
                @Html.TextBoxFor(m => m.EmailAddress, new { @class = "form-control", @placeholder = "Contact Email" })
            </div>
        </div>

        <div class="row">
            <div class="form-group col-sm-4">
                @Html.LabelFor(m => m.Address)
                @Html.TextAreaFor(m => m.Address, new { @class="form-control", @placeholder = "Address Details"})
            </div>
            <div class="form-group col-sm-4">
                @Html.LabelFor(m => m.ContactInfo)
                @Html.TextAreaFor(m => m.ContactInfo, new { @class = "form-control", @placeholder = "Contact Information" })
            </div>
            <div class="col-sm-offset-4"></div>
        </div>

        <div class="row">
            <div class="form-group col-sm-4">
                @Html.LabelFor(m => m.PostCode)
                @Html.TextBoxFor(m => m.PostCode, new { @class = "form-control", placeholder = "Post Code" })
            </div>
            <div class="form-group col-sm-4">
                @Html.LabelFor(m => m.DateJoined)
                @Html.TextBoxFor(m => m.DateJoined, "{0:yyyy-MM-dd}", new { @class = "form-control", @type = "date" })
            </div>
            <div class="col-sm-offset-4"></div>
        </div>

        <div class="row">
            <div class="form-group col-lg-8">
                @Html.LabelFor(m => m.Note)
                @Html.TextAreaFor(m => m.Note, new { @class = "form-control new-cust-note", @placeholder = "Initial Notes..." })
            </div>
            <div class="col-lg-offset-4"></div>
        </div>

        <br />

        if (Model.Id != 0)
        {
            <button class="btn btn-success">Save Customer</button>
        }
        else
        {
            <button class="btn btn-success">Add Customer</button>
        }

    }

@section scripts {

@Scripts.Render("~/scripts/formscripts/customers/customer-form.js")



}

DLS_Technologies/Views/Customers/CustomerParent.cshtml
@model DLS_Technologies.Models.Customer
@{
    ViewBag.Title = Model.Id != 0 ? Model.Name : "New Customer";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@Model.Name</h2>
<hr />
@Html.ActionLink("Back", "Index", "Customers", new { }, null)<br />

<input type="hidden" id="Id" name="Id" value="@Model.Id">

<div class="row" style="margin-bottom:10px; margin-left:-15px;">
    <button id="cust-info-btn" class="btn btn-link cust-btns" data-btn-id="1">Customer Info</button>
    <button id="site-info-btn" class="btn btn-link cust-btns" data-btn-id="2">Site Info</button>
    <button id="server-info-btn" class="btn btn-link cust-btns" data-btn-id="3">Servers</button>
    <button id="account-info-btn" class="btn btn-link cust-btns" data-btn-id="4">Account Info</button>
</div>

<div id="customer-partial"></div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/scripts/formscripts/customers/customer-parent.js")
}

DLS_Technologies/Views/Customers/Index.cshtml
@model IEnumerable<DLS_Technologies.Models.Customer>
@{
    ViewBag.Title = "Customers";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@ViewBag.Title</h2>
<hr />

@Html.ActionLink("Add New Customer", "NewCustomer", "Customers", new { @class = "btn btn-primary" })
<br /><br />

@{ 
    if (!Model.Any())
    {
        <h3>No customers have been created. </h3>
    }
    else
    {
        <table id="customerTable" class="table table-hover table-bordered">
            <thead>
                <tr>
                    <th>Customer Name</th>
                    <th>Address</th>
                </tr>
            </thead>
            <tbody>
                @{ 
                    foreach (var customer in Model)
                    {
                        <tr data-customer-id="@customer.Id">
                            <td>@customer.Name</td>
                            <td>@customer.Address</td>
                        </tr>
                    }
                }
            </tbody>
        </table>
    }
}

@section scripts {

@Scripts.Render("~/scripts/formscripts/customers/customer-index.js")

}

DLS_Technologies/Views/Customers/_AccountInfo.cshtml
@model DLS_Technologies.Models.Customer

@using (Html.BeginForm())
{
    @Html.ValidationSummary()
    @Html.AntiForgeryToken()
    <input type="hidden" id="Id" name="Id" value="@Model.Id">
}

DLS_Technologies/Views/Customers/_CustomerDetails.cshtml
@model DLS_Technologies.Models.Customer

@using (Html.BeginForm())
{
    @Html.ValidationSummary()
    @Html.AntiForgeryToken()
    <input type="hidden" id="Id" name="Id" value="@Model.Id">

    <div class="row">
        <div class="form-group col-sm-4">
            @Html.LabelFor(m => m.AccountTypeId)
            @Html.ValueFor(m => m.AccountType.Name)
        </div>
        @if (Model.MonthlySiteVisitDate != null)
        {
            <div class="form-group col-sm-4">
                @Html.LabelFor(m => m.MonthlySiteVisitDate)
                @Html.ValueFor(m => m.MonthlySiteVisitDate, "{0:dd/MM/yyyy}")
            </div>
        }
    </div>

        <div class="row">   
            <div class="form-group col-sm-4">
                @Html.LabelFor(m => m.ContactOnSite)
                @Html.ValueFor(m => m.ContactOnSite)
            </div>
            <div class="form-group col-sm-4">
                @Html.LabelFor(m => m.EmailAddress)
                @Html.ValueFor(m => m.EmailAddress)
            </div>
            <div class="col-sm-offset-4"></div>
        </div>

        <div class="row">
            <div class="form-group col-sm-4">
                @Html.LabelFor(m => m.Address)
                @Html.ValueFor(m => m.Address)
            </div>
            <div class="form-group col-sm-4">
                @Html.LabelFor(m => m.ContactInfo)
                @Html.ValueFor(m => m.ContactInfo)
            </div>
            <div class="col-sm-offset-4"></div>
        </div>

        <div class="row">
            <div class="form-group col-sm-4">
                @Html.LabelFor(m => m.PostCode)
                @Html.ValueFor(m => m.PostCode)
            </div>
            <div class="form-group col-sm-4">
                @Html.LabelFor(m => m.DateJoined)
                @Html.ValueFor(m => m.DateJoined, "{0:dd/MM/yyyy}")
            </div>
            <div class="col-sm-offset-4"></div>
        </div>

        <br />

        <div id="customer-notes-partial"></div>        
}
        <br /><br />

        <div class="cust-details-btns">
            @Html.ActionLink("Edit", "Edit", "Customers", new { @id = @Model.Id }, new { @class= "btn btn-success" } )
            <button id="del-customer-btn" class="btn btn-primary" data-customer-id="@Model.Id">Delete Customer</button>
        </div>


@Scripts.Render("~/scripts/formscripts/customers/customer-details.js")

   

DLS_Technologies/Views/Customers/_CustomerNotes.cshtml
@model DLS_Technologies.ViewModels.CustomerViewModels.CustomerViewModel

<div class="row">
    <div class="form-group col-sm-8">
        @Html.LabelFor(m => m.Note)
        <br />        
        <div id="cust-note-edit">
            @Html.TextAreaFor(m => m.Note, new { @class = "form-control new-cust-note", @placeholder = "Click Edit to add a note...", @readonly = true })
        </div>
        <br />
        <div class="siteinfo-btns">
            <button id="edit-notes-btn" class="btn btn-link">Edit</button>
            <button id="save-notes-btn" class="btn btn-link" data-customer-id="@Model.Id">Save</button>
        </div>
    </div>
    <div class="col-sm-offset-4"></div>
</div>

@Scripts.Render("~/scripts/formscripts/customers/customer-notes.js")

DLS_Technologies/Views/Customers/_ServerInfo.cshtml
@model DLS_Technologies.ViewModels.CustomerViewModels.ServerViewModel

@using (Html.BeginForm())
{
    @Html.ValidationSummary()
    @Html.AntiForgeryToken()    
    @Html.HiddenFor(m => m.CustomerId)

    <div id="servers-table-partial"></div>
    <br /><br />

    <div class="row">
        <div class="form-group col-sm-2">
            @Html.LabelFor(m => m.ServerName)
            @Html.TextBoxFor(m => m.ServerName, new { @class = "form-control" })
        </div>

        <div class="form-group col-sm-2">
            @Html.LabelFor(m => m.PublicIpAddress)
            @Html.TextBoxFor(m => m.PublicIpAddress, new { @class = "form-control" })
        </div>

        <div class="form-group col-sm-2">
            @Html.LabelFor(m => m.PrivateIpAddress)
            @Html.TextBoxFor(m => m.PrivateIpAddress, new { @class = "form-control" })
        </div>

        <div class="form-group col-sm-2">
            @Html.LabelFor(m => m.Port)
            @Html.TextBoxFor(m => m.Port, new { @class = "form-control" })
        </div>

        <div class="form-group col-sm-2">
            @Html.LabelFor(m => m.UserName)
            @Html.TextBoxFor(m => m.UserName, new { @class = "form-control" })
        </div>

        <div class="form-group col-sm-2">
                @Html.LabelFor(m => m.Password)
                @Html.TextBoxFor(m => m.Password, new { @class = "form-control" })            
        </div>
        
    </div>

    <div id="add-btn" class="row col-sm-2 sever-btn-div">
        <button id="add-server-btn" class="btn btn-success">Add</button>
    </div>
        <div id="edit-btns" hidden="hidden" class="row col-sm-2 sever-btn-div">
            <button id="delete-server-btn" class="btn btn-primary">Delete</button>
            <button id="save-server-btn" class="btn btn-success">Save</button>
        </div>





}

@Scripts.Render("~/scripts/formscripts/customers/serverinfo.js")

DLS_Technologies/Views/Customers/_ServersTable.cshtml
@model DLS_Technologies.ViewModels.CustomerViewModels.ServerViewModel

<input type="hidden" id="ServerId" name="ServerId" value="0">

<div class="row servers-table">
    @{
        if (!Model.Servers.Any())
        {
            <div > <h3>No Servers have been added.</h3></div>
        }
        else
        {
            <table id="servers-table" class="table table-bordered">
                <thead>
                    <tr>
                        <td><b>Server Name</b></td>
                        <td><b>Public IP</b></td>
                        <td><b>Private IP</b></td>
                        <td><b>Port</b></td>
                        <td><b>Domain\Username</b></td>
                        <td><b>Password</b></td>
                        <td><b>Web Connect</b></td>
                        <td><b>Remote Desktop</b></td>
                        <td></td>
                    </tr>
                </thead>
                <tbody>
                    @{
                        foreach (var item in Model.Servers)
                        {
                            <tr>
                                
                                <td id="server-name"><b>@item.ServerName</b></td>
                                <td id="public-ip">@item.PublicIpAddress</td>
                                <td id="private-ip">@item.PrivateIpAddress</td>
                                <td id="port">@item.Port</td>
                                <td id="username">@item.UserName</td>
                                <td id="password">@item.Password</td>
                                <td><button class="btn btn-link js-web-connect"><b>Connect</b></button></td>
                                <td><button class="btn btn-link js-rdp-connect"><b>Connect</b></button></td>
                                <td><button data-server-id="@item.Id" class="btn btn-link js-edit-btn">Edit</button></td>
                            </tr>
                        }
                    }
                </tbody>
            </table>
        }
    }


</div>



@Scripts.Render("~/scripts/formscripts/customers/servers-table.js")