DLS_Technologies/Models/ExpensesModels/Expense.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace DLS_Technologies.Models.ExpensesModels
{
    public class Expense
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }

        public string Description { get; set; }

        [Required]
        public DateTime? Date { get; set; }

        public DateTime DateTime { get; set; }

        public double? Cost { get; set; }
        
        public Customer Customer { get; set; }

        [Display(Name = "Customer")]
        public int? CustomerId { get; set; }
        
        public ExpenseType ExpenseType { get; set; }

        [Display(Name = "Expense Type")]
        public byte ExpenseTypeId { get; set; }
              
        public string Origin { get; set; }        
        
        public string Destination { get; set; }

        [Display(Name = "Odometer Start")]
        public int? OdometerStart { get; set; }

        [Display(Name = "Odometer End")]
        public int? OdometerEnd { get; set; }

        public ExpenseForm ExpenseForm { get; set; }

        [Display(Name = "Expense Form")]
        public int ExpenseFormId { get; set; }
        
        [Display(Name = "Total Miles")]
        public double? TotalMiles { get; set; }




    }
}

DLS_Technologies/Controllers/Api/Expenses/ExpenseFormsController.cs
using DLS_Technologies.Models;
using DLS_Technologies.Models.ExpensesModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Http.Formatting;
using System.Web.Http;

namespace DLS_Technologies.Controllers.Api
{
    public class ExpenseFormsController : ApiController
    {
        private ApplicationDbContext _context;

        public ExpenseFormsController()
        {
            _context = new ApplicationDbContext();
        }


        // DELETE api/expenseforms/1
        [HttpDelete]
        [System.Web.Mvc.ValidateAntiForgeryToken]
        public void DeleteExpenseForm(int id)
        {
            var expenseFormInDb = _context.ExpenseForms.SingleOrDefault(e => e.Id == id);

            if (expenseFormInDb == null)
                throw new HttpResponseException(HttpStatusCode.NotFound);

            _context.ExpenseForms.Remove(expenseFormInDb);
            _context.SaveChanges();
        }

        // UPDATE api/expenseforms/1
        [HttpPut]
        [System.Web.Mvc.ValidateAntiForgeryToken]
        public void UpdateExpenseFormName(FormDataCollection formData)
        {
            var id = Convert.ToInt32(formData.Get("Id"));
            var name = formData.Get("Name");

            var expenseFormInDb = _context.ExpenseForms.SingleOrDefault(e => e.Id == id);

            if (expenseFormInDb == null)
                throw new HttpResponseException(HttpStatusCode.NotFound);

            expenseFormInDb.Name = name;
            _context.SaveChanges();
        }



    }
}

DLS_Technologies/Controllers/Api/Expenses/ExpensesController.cs
using DLS_Technologies.Models;
using DLS_Technologies.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;

namespace DLS_Technologies.Controllers.Api
{
    public class ExpensesController : ApiController
    {
        ApplicationDbContext _context;

        public ExpensesController()
        {
            _context = new ApplicationDbContext();
        }
        
        [HttpDelete]
        [System.Web.Mvc.ValidateAntiForgeryToken]
        public void DeleteExpense(int id)
        {
            var expenseInDb = _context.Expenses.FirstOrDefault(e => e.Id == id);
            var expenseForm = _context.Expenses.Where(e => e.Id == id).Select(e => e.ExpenseForm).FirstOrDefault();

            if (expenseInDb == null)
                throw new HttpResponseException(HttpStatusCode.NotFound);

            expenseForm.TotalCost -= expenseInDb.Cost.Value;

            _context.Expenses.Remove(expenseInDb);
            _context.SaveChanges();
        }



    }
}

DLS_Technologies/Controllers/Expenses/ExpenseFormsController.cs
using DLS_Technologies.Models;
using DLS_Technologies.Models.ExpensesModels;
using DLS_Technologies.ViewModels;
using System.Data.Entity;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using System.Net;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Threading.Tasks;
using Microsoft.AspNet.Identity.EntityFramework;
using System.Net.Http.Formatting;

namespace DLS_Technologies.Controllers
{

    /// <summary>
    /// TODO: Add validation for each HTTP Request.
    /// TODO: Use DTOs instead of domain model.
    /// </summary>


    public class ExpenseFormsController : Controller
    {
        /// Application DB context        
        protected ApplicationDbContext _context { get; set; }
       
        /// User manager - attached to application DB context        
        protected UserManager<ApplicationUser> _userManager { get; set; }

        public ExpenseFormsController()
        {
            _context = new ApplicationDbContext();
            _userManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(_context));
            
        }

        public ActionResult Index()
        {
            var _user = _userManager.FindById(User.Identity.GetUserId());
            var expenseForms = _context.ExpenseForms.Where(e => e.UserId == _user.Id).ToList();            

            return View(expenseForms);
        }                     
        
        // GET: Expenses
        [HttpPost]
        public ActionResult SaveExpenseForm(ExpenseFormViewModel expenseForm)
        {
            if (!ModelState.IsValid)            
                return View("Index");           


            var _user = _userManager.FindById(User.Identity.GetUserId());

            var expenseForms = _context.ExpenseForms.Where(e => e.UserId == _user.Id).ToList();          

            if (expenseForm.Id == 0)
            {
                var expenseFormToSave = new ExpenseForm
                {
                    Name = expenseForm.Name,
                    DateAdded = DateTime.Now,
                    TotalCost = 0,
                    UserId = _user.Id,
                    User = _user
                };
                _context.ExpenseForms.Add(expenseFormToSave);
            }                
            else
            {
                var _expenseFormInDb = _context.ExpenseForms.First(e => e.Id == expenseForm.Id);
                _expenseFormInDb.Name = expenseForm.Name;
            }

            _context.SaveChanges();          

            return RedirectToAction("Index");

        }

        public ActionResult ShowExpenses(int expenseFormId)
        {
            var expenseForm = _context.ExpenseForms.Include(e => e.User).SingleOrDefault(e => e.Id == expenseFormId);
            var viewModel = new ExpenseFormViewModel
            {
                ExpenseForm = expenseForm,
                Expenses = _context.Expenses.Include(e => e.ExpenseType).Where(e => e.ExpenseFormId == expenseFormId).ToList(),
                User = expenseForm.User
                
            };

            var name = !String.IsNullOrEmpty(viewModel.User.FullName) ? viewModel.User.FullName : viewModel.User.FirstName + " " + viewModel.User.LastName;

            ViewBag.Title = viewModel.ExpenseForm.Name + " - " + name;            

            return View("ShowExpensesForm", viewModel);
        }

        

    }
}

DLS_Technologies/Controllers/Expenses/ExpensesController.cs
using DLS_Technologies.Models;
using DLS_Technologies.Models.ExpensesModels;
using DLS_Technologies.ViewModels;
using System.Data.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net;
using Microsoft.AspNet.Identity;

namespace DLS_Technologies.Controllers
{
    /// <summary>
    /// TODO: Add validation for each HTTP Request.
    /// TODO: Use DTOs instead of domain model.
    /// </summary>
    
    public class ExpensesController : Controller
    {
        ApplicationDbContext _context;

        public ExpensesController()
        {
            _context = new ApplicationDbContext();
        }               

        // GET /expenses/
        public ActionResult Index()
        {
            var expenseForms = _context.ExpenseForms.ToList();
            var expenseForm = new ExpenseForm();
            return View(expenseForms);
        }   
        

        // GET /expenses/getexpense/1
        public ActionResult GetExpense(int id)
        {         
            var expense = _context.Expenses.Include(e => e.ExpenseType).FirstOrDefault(e => e.Id == id);
            var expenseTypes = _context.ExpenseTypes.ToList();
            var expenseForm = _context.ExpenseForms.FirstOrDefault(e => e.Id == expense.ExpenseFormId);

            if (expense == null)
                return Content("Expense is null");

            ViewBag.Title = "Expense - " + expense.ExpenseType.Name;

            var viewModel = new ExpenseViewModel
            {
                Id = expense.Id,
                ExpenseTypes = expenseTypes,
                ExpenseTypeId = expense.ExpenseTypeId,
                ExpenseType = expense.ExpenseType,
                ExpenseForm = expenseForm,
                ExpenseFormId = expense.ExpenseFormId,
                Date = expense.Date,
                Cost = expense.Cost
            };

            return View("ExpenseForm", viewModel);
            
        }
        

        // GET /expenses/new
        public ActionResult NewExpense(int expenseFormId)
        {
            var expenseTypes = _context.ExpenseTypes.ToList();

            var viewModel = new ExpenseViewModel
            {
                 ExpenseTypes = expenseTypes,
                 ExpenseForm = _context.ExpenseForms.Single(e => e.Id == expenseFormId),
                 ExpenseFormId = expenseFormId,
                 Date = DateTime.Now
            };

            return View("ExpenseForm", viewModel);           
        }

        
        // POST /expenses/save/1
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Save(Expense expense)
        {
            if (!ModelState.IsValid)
            {
                var expenseTypes = _context.ExpenseTypes.ToList();

                var viewModel = new ExpenseViewModel
                {
                    ExpenseTypes = expenseTypes,
                    ExpenseForm = _context.ExpenseForms.Single(e => e.Id == expense.ExpenseFormId)
                };

                return View("ExpenseForm", viewModel);
            }



            var parsedOrigin = "";
            var parsedDestination = "";

            if (expense.Cost == null)
                expense.Cost = 0.00;

            var expenseForm = _context.ExpenseForms.FirstOrDefault(e => e.Id == expense.ExpenseFormId);

            if(!String.IsNullOrEmpty(expense.Origin) || !String.IsNullOrEmpty(expense.Destination))
            {
                if (String.IsNullOrEmpty(expense.Origin))
                    expense.Origin = "";
                if (String.IsNullOrEmpty(expense.Destination))
                    expense.Destination = "";

                if (!expense.Origin.Contains(",") && !expense.Destination.Contains(","))
                {
                    if (expense.Id == 0)
                    {
                        expense.DateTime = DateTime.Now;
                        expenseForm.TotalCost += expense.Cost;
                        _context.Expenses.Add(expense);
                    }
                    else
                    {
                        var expenseInDb = _context.Expenses.Single(e => e.Id == expense.Id);                        
                        expenseInDb.CustomerId = expense.CustomerId;
                        expenseInDb.Date = expense.Date;
                        expenseInDb.DateTime = expense.DateTime;
                        expenseInDb.Destination = expense.Destination;
                        expenseInDb.ExpenseFormId = expense.ExpenseFormId;
                        expenseInDb.ExpenseTypeId = expense.ExpenseTypeId;
                        expenseInDb.OdometerEnd = expense.OdometerEnd;
                        expenseInDb.OdometerStart = expense.OdometerStart;
                        expenseInDb.Origin = expense.Origin;
                        expenseInDb.TotalMiles = expense.TotalMiles;

                        expenseForm.TotalCost -= expenseInDb.Cost;
                        expenseForm.TotalCost += expense.Cost;

                        expenseInDb.Cost = expense.Cost;
                    }
                }
                else
                {
                    if (expense.Origin.Contains(","))
                        parsedOrigin = expense.Origin.Substring(0, expense.Origin.IndexOf(","));
                    else
                        parsedOrigin = expense.Origin;

                    if (expense.Destination.Contains(","))
                        parsedDestination = expense.Destination.Substring(0, expense.Destination.IndexOf(","));
                    else
                        parsedDestination = expense.Destination;

                    if (expense.Id == 0)
                    {
                        expense.Origin = parsedOrigin;
                        expense.Destination = parsedDestination;
                        expenseForm.TotalCost += expense.Cost;
                        expense.DateTime = DateTime.Now;
                        _context.Expenses.Add(expense);
                    }
                    else
                    {
                        var expenseInDb = _context.Expenses.Single(e => e.Id == expense.Id);
                        expenseInDb.CustomerId = expense.CustomerId;
                        expenseInDb.Date = expense.Date;
                        expenseInDb.DateTime = expense.DateTime;
                        expenseInDb.Destination = parsedDestination;
                        expenseInDb.ExpenseFormId = expense.ExpenseFormId;
                        expenseInDb.ExpenseTypeId = expense.ExpenseTypeId;
                        expenseInDb.OdometerEnd = expense.OdometerEnd;
                        expenseInDb.OdometerStart = expense.OdometerStart;
                        expenseInDb.Origin = parsedOrigin;
                        expenseInDb.TotalMiles = expense.TotalMiles;

                        expenseForm.TotalCost -= expenseInDb.Cost;
                        expenseForm.TotalCost += expense.Cost;

                        expenseInDb.Cost = expense.Cost;
                    }
                }
            }
            else 
            {
                if (expense.Id == 0)
                {
                    expenseForm.TotalCost += expense.Cost;
                    expense.DateTime = DateTime.Now;
                    _context.Expenses.Add(expense);
                }
                else
                {
                    var expenseInDb = _context.Expenses.Single(e => e.Id == expense.Id);
                    expenseInDb.CustomerId = expense.CustomerId;
                    expenseInDb.Date = expense.Date;
                    expenseInDb.DateTime = expense.DateTime;
                    expenseInDb.Description = expense.Description;
                    expenseInDb.ExpenseFormId = expense.ExpenseFormId;
                    expenseInDb.ExpenseTypeId = expense.ExpenseTypeId;

                    expenseForm.TotalCost -= expenseInDb.Cost;
                    expenseForm.TotalCost += expense.Cost;

                    expenseInDb.Cost = expense.Cost;
                }                
            }
            
            _context.SaveChanges();

            return RedirectToAction("ShowExpenses", "ExpenseForms", new { expenseFormId = expense.ExpenseFormId });
        }

        [HttpDelete]
        [ValidateAntiForgeryToken]
        public void DeleteExpense(int id)
        {
            var expenseInDb = _context.Expenses.FirstOrDefault(e => e.Id == id);
            var expenseForm = _context.Expenses.Where(e => e.Id == id).Select(e => e.ExpenseForm).FirstOrDefault();
            
            expenseForm.TotalCost -= expenseInDb.Cost.Value;

            _context.Expenses.Remove(expenseInDb);
            _context.SaveChanges();
           
        }

        //-------------------------------------------------------------------------------------
        // Partials 
        // ------------------------------------------------------------------------------------



        public ActionResult LoadMileageFormat(int id)
        {
            if (id == 1)
            {
                var viewModel = new MileageFormViewModel();
                return PartialView("_OdometerForm", viewModel);
            }
            else
            {
                var viewModel = new MileageFormViewModel();
                return PartialView("_GoogleMapsForm", viewModel);
            }
        }        

        public ActionResult LoadExpensePartial(int id)
        {
            if (id == 1)
            {
                var mileageViewModel = new MileageFormViewModel();
                return PartialView("_MileageForm", mileageViewModel);
            }
            else
            {
                var expenseViewModel = new ExpenseViewModel();
                return PartialView("_OtherExpenseForm", expenseViewModel);
            }
        }

        public ActionResult LoadEditExpensePartial(int id, int expenseType)
        {

DLS_Technologies/Views/Expenses/ExpenseForm.cshtml
@model DLS_Technologies.ViewModels.ExpenseViewModel
@{
    var title = Model.Id == 0 ? ViewBag.Title = "New Expense" : "Edit Expense";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>@title - @Html.ValueFor(m => m.ExpenseForm.Name)</h3>
<hr />
@Html.ActionLink("Back", "ShowExpenses", "ExpenseForms", new { expenseFormId = Model.ExpenseForm.Id}, null)
<br /><br />

    @using (Html.BeginForm("Save", "Expenses"))
    {
        @Html.ValidationSummary()
        @Html.AntiForgeryToken()  
        @Html.HiddenFor(m => m.Id)
        @Html.HiddenFor(m => m.ExpenseFormId)

        <div class="form-group">
            @Html.LabelFor(m => m.Date)
            @Html.TextBoxFor(m => m.Date, "{0:yyyy-MM-dd}", new { @class = "form-control", @type = "date" })     
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.ExpenseTypeId)
            @Html.DropDownListFor(m => m.ExpenseTypeId, new SelectList(Model.ExpenseTypes, "Id", "Name", "1"), "Select Expense Type", new { @class = "form-control", @onChange = "LoadExpenseForms()" })
        </div>        

        <div id="PartialDiv">
        </div>

        {
            if (Model.Id == 0)
            {
                <button type="submit" class="btn btn-success">Add Expense</button>
            }
            else
            {
                <button type="submit" class="btn btn-success">Update Expense</button>
                <button type="submit" id="delete-btn" data-expense-id="@Model.Id" data-form-id="@Model.ExpenseFormId" class="btn btn-primary">Delete Expense</button>
            }
        }

    }

@section scripts {
    @Scripts.Render("~/bundles/jqueryval")    
    @Scripts.Render("~/scripts/formscripts/expenses/expense-form.js")
}

DLS_Technologies/Views/Expenses/NewExpenseForm.cshtml
@model DLS_Technologies.ViewModels.ExpenseViewModel
@{
    ViewBag.Title = "Add New Expense";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<br />
<h2>@ViewBag.Title - @Html.ValueFor(m => m.ExpenseForm.Name)</h2>
<br />
@Html.ActionLink("Back", "ShowExpenses", "ExpenseForms", new { expenseFormId = Model.ExpenseForm.Id}, null)
<br /><br />

    @using (Html.BeginForm("Save", "Expenses"))
     {
        @Html.ValidationSummary()
        @Html.AntiForgeryToken()  
        @Html.HiddenFor(m => m.Id)
        @Html.HiddenFor(m => m.ExpenseFormId)

        <div class="form-group">
            @Html.LabelFor(m => m.Date)
            @Html.TextBoxFor(m => m.Date, "{0:yyyy-MM-dd}", new { @class = "form-control", @type = "date" })          
            @Html.ValidationMessageFor(m => m.Date)
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.ExpenseTypeId)
            @Html.DropDownListFor(m => m.ExpenseTypeId, new SelectList(Model.ExpenseTypes, "Id", "Name", "1"), "Select Expense Type",  new { @class = "form-control", @onChange = "LoadExpenseForms()" })
            @Html.ValidationMessageFor(m => m.ExpenseTypeId)
        </div>        

        <div id="PartialDiv">
        </div>       

        <button type="submit" class="btn btn-success">Add Expense</button>          
     }

@section scripts 
{

    @Scripts.Render("~/bundles/jqueryval")    

    <script>
        function LoadExpenseForms(id) {
            if (id == null)
                var id = $("#ExpenseTypeId").val();
            $.ajax({
                type: "GET",
                url: "/expenses/loadpartial/" + id,
                success: function (result) {
                    $("#PartialFormatDiv").empty();
                    $("#PartialDiv").empty();                   
                    $("#PartialDiv").html(result);

                    if (id == 1) {
                        $.ajax({
                            method: "GET",
                            url: "/expenses/loadmileageformat/" + 1,
                            success: function (result) {
                                $("#PartialFormatDiv").empty();
                                $("#PartialFormatDiv").html(result);
                            }
                        })
                    }
                }
            });
        }

        $(document).ready(function () {
            LoadExpenseForms(1);            
        })
                       
    </script>


    

}

DLS_Technologies/Views/Expenses/ViewExpenseForm.cshtml
@model DLS_Technologies.ViewModels.ExpenseViewModel
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<br />
<h2>@ViewBag.Title</h2>

@Html.ActionLink("Back", "ShowExpenses", "ExpenseForms", new { id = Model.ExpenseFormId }, null)
<br /><br />
@using (Html.BeginForm("Save", "Expenses"))
{
    @Html.ValidationSummary()
    @Html.AntiForgeryToken()
    @Html.HiddenFor(m => m.Id)
    @Html.HiddenFor(m => m.ExpenseFormId)

    <div class="form-group">
        @Html.LabelFor(m => m.Date)
        @Html.TextBoxFor(m => m.Date, "{0:yyyy-MM-dd}", new { @class = "form-control", @type = "date" })
        @Html.ValidationMessageFor(m => m.Date)
    </div>
    
      
    <div class="form-group">
        @Html.LabelFor(m => m.ExpenseTypeId)
        @Html.DropDownListFor(m => m.ExpenseTypeId, new SelectList(Model.ExpenseTypes, "Id", "Name"), new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.ExpenseTypeId)
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Description)
        @Html.TextAreaFor(m => m.Description, new { @class="form-control" })
        @Html.ValidationMessageFor(m => m.Description)
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Cost)
        @Html.TextBoxFor(m => m.Cost, "{0:n2}", new { @class="form-control" })
        @Html.ValidationMessageFor(m => m.Cost)

    </div>


    <button type="submit" class="btn btn-success">Update Expense</button>
    <button type="submit" id="delete-btn" data-expense-id="@Model.Id" data-form-id="@Model.ExpenseFormId" class="btn btn-primary">Delete Expense</button>


}

@section scripts
{
    <script>
        $(document).ready(function() {
            $("#delete-btn").on("click", function (e) {
                e.preventDefault();
                var button = $(this);
                var id = button.attr("data-form-id");
                bootbox.confirm("Are you sure you want to delete this Expense?", (result) => {
                    if (result) {
                        $.ajax({
                            method: "DELETE",
                            url: "/api/expenses/" + button.attr("data-expense-id"),
                            success: () => {
                                console.log(id);
                                window.location.href = "/ExpenseForms/ShowExpenses/" + id
                            }
                        });
                    };
                });
            });
        })
    </script>
}

DLS_Technologies/Views/Expenses/_GoogleMapsForm.cshtml
@model DLS_Technologies.ViewModels.MileageFormViewModel


@Html.HiddenFor(m => m.DateTime)

<div class="row">
    <div class="form-group col-sm-4">
        @Html.LabelFor(m => m.Origin)
        @Html.TextBoxFor(m => m.Origin, new { @class = "form-control", @placeholder = "Enter Origin" })
        @Html.ValidationMessageFor(m => m.Origin)
    </div>

    <div class="form-group col-sm-4">
        @Html.LabelFor(m => m.Destination)
        @Html.TextBoxFor(m => m.Destination, new { @class = "form-control", @placeholder = "Enter Destination" })
        @Html.ValidationMessageFor(m => m.Destination)
    </div>
    <div class="col-sm-offset-4"></div>
</div>

<div class="form-group">
    @Html.LabelFor(m => m.TotalMiles)
    @Html.TextBoxFor(m => m.TotalMiles, new { @class = "form-control", @type = "number" })
    @Html.ValidationMessageFor(m => m.TotalMiles)
</div>


<div id="result" class="validation-failed"></div>

<div class="form-group">
    @Html.LabelFor(m => m.Cost)
    @Html.TextBoxFor(m => m.Cost, new { @class = "form-control", @readonly = "readonly", @type = "number" })
    @Html.ValidationMessageFor(m => m.Cost)
</div>
    

@Scripts.Render("~/scripts/formscripts/expenses/googlemaps-form.js")

DLS_Technologies/Views/Expenses/_MileageForm.cshtml
@model DLS_Technologies.ViewModels.MileageFormViewModel


<div id="target" class="form-group">
    <label class="radio-inline"><input id="odometerRadBtn" data-radioBtn-id="1" checked="checked" type="radio" class="js-mileage-radiobtn" name="optradio" value="odometer">Odometer</label>
    <label class="radio-inline"><input id="googleMapsRadBtn" data-radioBtn-id="2" type="radio" class="js-mileage-radiobtn" name="optradio" value="googleMaps">Google Maps</label>    
</div>

<div id="PartialFormatDiv">
</div>

@Scripts.Render("~/scripts/formscripts/expenses/mileage-form.js")

DLS_Technologies/Views/Expenses/_OdometerForm.cshtml
@model DLS_Technologies.ViewModels.MileageFormViewModel


@Html.HiddenFor(m => m.DateTime)

<div class="row">
    <div class="form-group col-sm-4">
        @Html.LabelFor(m => m.Origin)
        @Html.TextBoxFor(m => m.Origin, new { @class = "form-control", @placeholder = "Enter Origin" })
        @Html.ValidationMessageFor(m => m.Origin)
    </div>

    <div class="form-group col-sm-4">
        @Html.LabelFor(m => m.Destination)
        @Html.TextBoxFor(m => m.Destination, new { @class = "form-control", @placeholder = "Enter Destination" })
        @Html.ValidationMessageFor(m => m.Destination)
    </div>
    <div class="col-sm-offset-4"></div>
</div>
<div class="row">
    <div class="form-group col-sm-4">
        @Html.LabelFor(m => m.OdometerStart)
        @Html.TextBoxFor(m => m.OdometerStart, new { @class = "form-control", @placeholder = "Enter Value", @type = "number" })
        @Html.ValidationMessageFor(m => m.OdometerStart)
    </div>

    <div class="form-group col-sm-4">
        @Html.LabelFor(m => m.OdometerEnd)
        @Html.TextBoxFor(m => m.OdometerEnd, new { @class = "form-control", @placeholder = "Enter Value", @type = "number" })
        @Html.ValidationMessageFor(m => m.OdometerEnd)
    </div>
</div>

<div id="result" class="validation-failed"></div>

<div class="form-group">
    @Html.LabelFor(m => m.TotalMiles)
    @Html.TextBoxFor(m => m.TotalMiles, new { @class = "form-control" })
    @Html.ValidationMessageFor(m => m.TotalMiles)
</div>

<div class="form-group">
    @Html.LabelFor(m => m.Cost)
    @Html.TextBoxFor(m => m.Cost, new { @class = "form-control", @readonly = "readonly" })
    @Html.ValidationMessageFor(m => m.Cost)
</div>

@Scripts.Render("~/scripts/formscripts/expenses/odometer-form.js")

DLS_Technologies/Views/Expenses/_OtherExpenseForm.cshtml
@model DLS_Technologies.ViewModels.ExpenseViewModel


@Html.HiddenFor(m => m.DateTime)

<div class="form-group">
    @Html.LabelFor(m => m.Description)
    @Html.TextAreaFor(m => m.Description, new { @class = "form-control" })
    @Html.ValidationMessageFor(m => m.Description)
</div>

<div class="form-group">
    @Html.LabelFor(m => m.Cost)
    @Html.TextBoxFor(m => m.Cost, new { @class = "form-control" })
    @Html.ValidationMessageFor(m => m.Cost)
</div>

@Scripts.Render("~/bundles/jqueryval")